import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Footer from "@/components/ui/footer";
import QueryProvider from "../providers/queryProvider";
// import Header from "@/components/ui/header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <QueryProvider>
        <body className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </QueryProvider>
    </html>
  );
}
